name = "Docker"
uuid = "15bad361-1dfa-5a14-8210-7c6791966b1c"
authors = ["Keno Fischer", "Dilum Aluthge", "contributors"]
version = "1.0.0-DEV"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
